name: Build Infinity Client

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Extract project
        run: |
          mkdir project
          unzip -q "InfinityV4-1.21.11-buildready.zip" -d project

      - name: Fix permissions
        run: |
          chmod -R u+rwX project/infinity

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.5.1'

      - name: Build Infinity Client
        working-directory: project/infinity
        run: gradle build --no-daemon

      - name: Upload compiled JAR
        uses: actions/upload-artifact@v4
        with:
          name: Infinity-Client
          path: project/infinity/build/libs/*.jar
